/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */


{RIL_UNSOL_NEIGHBORING_CELL_INFO, NULL, WAKE_PARTIAL},   //0 in alps/hardware/ril/include/telephony/ril.h
{RIL_UNSOL_NETWORK_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_PHB_READY_NOTIFICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SIM_INSERTED_STATUS, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RADIO_TEMPORARILY_UNAVAILABLE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_ME_SMS_STORAGE_FULL, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SMS_READY_NOTIFICATION, NULL, WAKE_PARTIAL},     //10 in alps/hardware/ril/include/telephony/ril.h
{RIL_UNSOL_SCRI_RESULT, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SIM_MISSING, NULL, WAKE_PARTIAL},
{RIL_UNSOL_GPRS_DETACH, NULL, WAKE_PARTIAL},
{RIL_UNSOL_ATCI_RESPONSE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SIM_RECOVERY, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VIRTUAL_SIM_ON, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VIRTUAL_SIM_OFF, NULL, WAKE_PARTIAL},
{RIL_UNSOL_INVALID_SIM, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_PS_NETWORK_STATE_CHANGED, radio::psNetworkStateChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_ACMT, NULL, WAKE_PARTIAL},
{RIL_UNSOL_EF_CSP_PLMN_MODE_BIT, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMEI_LOCK, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_MMRR_STATUS_CHANGED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SIM_PLUG_OUT, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SIM_PLUG_IN, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_ETWS_NOTIFICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_PLMN_CHANGED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_REGISTRATION_SUSPENDED, radio::registrationSuspendInd, WAKE_PARTIAL},
{RIL_UNSOL_STK_EVDL_CALL, NULL, WAKE_PARTIAL},
{RIL_UNSOL_DATA_PACKETS_FLUSH, NULL, WAKE_PARTIAL},//Add for Modem indication of RB release.
{RIL_UNSOL_FEMTOCELL_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_STK_SETUP_MENU_RESET, NULL, WAKE_PARTIAL},
{RIL_UNSOL_APPLICATION_SESSION_ID_CHANGED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_ECONF_SRVCC_INDICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMS_ENABLE_DONE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMS_DISABLE_DONE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMS_REGISTRATION_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_DEDICATE_BEARER_ACTIVATED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_DEDICATE_BEARER_MODIFIED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_DEDICATE_BEARER_DEACTIVATED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_RAC_UPDATE, NULL, WAKE_PARTIAL},//sm cause rac
{RIL_UNSOL_ECONF_RESULT_INDICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_MELOCK_NOTIFICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_CALL_FORWARDING, NULL, WAKE_PARTIAL},
{RIL_UNSOL_CRSS_NOTIFICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_INCOMING_CALL_INDICATION, radio::incomingCallInd, WAKE_PARTIAL},
{RIL_UNSOL_CIPHER_INDICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_CNAP, NULL, WAKE_PARTIAL}, //obsolete
{RIL_UNSOL_SIM_COMMON_SLOT_NO_CHANGED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_DATA_ALLOWED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_STK_CALL_CTRL, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VOLTE_EPS_NETWORK_FEATURE_SUPPORT, NULL, WAKE_PARTIAL},
{RIL_UNSOL_CALL_INFO_INDICATION, radio::callInfoInd, WAKE_PARTIAL},
{RIL_UNSOL_VOLTE_EPS_NETWORK_FEATURE_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SRVCC_HANDOVER_INFO_INDICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SPEECH_CODEC_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_MD_STATE_CHANGE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_REMOVE_RESTRICT_EUTRAN, NULL, WAKE_PARTIAL},//CC33
{RIL_UNSOL_MO_DATA_BARRING_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SSAC_BARRING_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SIP_CALL_PROGRESS_INDICATOR, NULL, WAKE_PARTIAL},
{RIL_UNSOL_ABNORMAL_EVENT, NULL, WAKE_PARTIAL},
{RIL_UNSOL_EMERGENCY_BEARER_SUPPORT_NOTIFY, NULL, WAKE_PARTIAL},
{RIL_UNSOL_INTER_3GPP_IRAT_STATE_CHANGE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_LTE_BG_SEARCH_STATUS, NULL, WAKE_PARTIAL},
{RIL_UNSOL_GMSS_RAT_CHANGED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_CDMA_CARD_TYPE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMS_ENABLE_START, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMS_DISABLE_START, NULL, WAKE_PARTIAL},
{RIL_UNSOL_IMSI_REFRESH_DONE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_EUSIM_READY, NULL, WAKE_PARTIAL},
{RIL_UNSOL_STK_BIP_PROACTIVE_COMMAND, NULL, WAKE_PARTIAL},
{RIL_UNSOL_WORLD_MODE_CHANGED, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VT_STATUS_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VT_RING_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VSIM_OPERATION_INDICATION, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SET_ATTACH_APN, radio::setAttachApnInd, WAKE_PARTIAL},
{RIL_UNSOL_MAL_AT_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_MAIN_SIM_INFO, NULL, WAKE_PARTIAL},
{RIL_UNSOL_TRAY_PLUG_IN, NULL, WAKE_PARTIAL},
{RIL_UNSOL_CALLMOD_CHANGE_INDICATOR, NULL, WAKE_PARTIAL},
{RIL_UNSOL_VIDEO_CAPABILITY_INDICATOR, NULL, WAKE_PARTIAL},
{RIL_UNSOL_LTE_ACCESS_STRATUM_STATE_CHANGE, NULL, WAKE_PARTIAL},
{RIL_UNSOL_SETUP_DATA_CALL_RESPONSE, NULL, WAKE_PARTIAL}
