LOCAL_PATH := $(call my-dir)

# Switch
MESS_UP_WITH_OPENSSL := nope

# Build OpenSSL
ifeq ($(MESS_UP_WITH_OPENSSL),true)

include $(CLEAR_VARS)
LOCAL_MODULE = libssl-static
LOCAL_MODULE_CLASS = STATIC_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .a
LOCAL_SRC_FILES = libopenssl/libssl-static.a
include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE = libcrypto-static
LOCAL_MODULE_CLASS = STATIC_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .a
LOCAL_SRC_FILES = libopenssl/libcrypto-static.a
include $(BUILD_STATIC_LIBRARY)

endif
