LOCAL_PATH:= $(call my-dir)

# ====== 64 bit library =====
include $(CLEAR_VARS)
LOCAL_MODULE := libepos
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .a
LOCAL_MULTILIB = 64
LOCAL_SRC_FILES_64 := libepos.a
include $(BUILD_PREBUILT)

# ====== 32 bit library =====
include $(CLEAR_VARS)
LOCAL_MODULE := libepos
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .a
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 := arm/libepos.a
include $(BUILD_PREBUILT)
